#! /bin/sh

sxhkd &
setxkbmap -v es
picom &
#xrandr -s 1600x900 &
exec /home/newvash/.config/polybar/launch.sh  &
feh --bg-fill --randomize /home/newvash/.wallpapers/ *
#feh --bg-fill -z /home/newvash/.wallpapers/*
bspc config pointer_modifier mod1

#### SI TENGO MAS MONITORES REALES####
#bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9

#bspc monitor -d               PARA PONERLE ICONOS POR LAS DUDAS QUE QUIERA

bspc monitor -d I II III IV V VI VII VIII IX X

#### BSPWM configuration ####

#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	          "#1e1e1e"
bspc config focused_border_color	      "#FF0000"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr

#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_Virtual-1)


bspc desktop ^1 -l monocle
bspc desktop ^2 -l monocle
bspc desktop ^5 -l monocle
bspc desktop ^6 -l monocle
bspc desktop ^9 -l monocle
bspc desktop ^10 -l monocle

# Rules
bspc rule -a tilix:Tiled desktop='^' follow=on
bspc rule -a tilix:Tmux desktop='^' follow=on
bspc rule -a Chromium desktop='^'
bspc rule -a Thunar desktop='^' state=pseudo_tiled
bspc rule -a TelegramDesktop desktop='^2' follow=on
bspc rule -a discord desktop='^2' follow=on
bspc rule -a Steam desktop='^2' state=floating
#bspc rule -a tilix:Newsboat state=floating center=on
bspc rule -a tilix:Ranger state=floating center=on
#bspc rule -a tilix:Pacui state=floating center=on
bspc rule -a tilix:Float state=floating

bspc rule -a Gnome-calculator state=floating
#bspc rule -a Gpick state=floating
bspc rule -a GParted state=floating
bspc rule -a Lxappearance state=floating center=true
bspc rule -a Pavucontrol state=floating
bspc rule -a qt5ct state=floating rectangle=700x470+0+0 center=on
#bspc rule -a mpv state=floating sticky=on rectangle=300x180+1060+475

bscp rule -a polybar manage=off
bspc rule -a Tint2 border=off manage=off layer=above state=floating
# bspc rule -a Mylaunchpad border=off manage=off
#bspc rule -a '*:Kunst' sticky=on layer=below border=off focus=off
# bspc rule -a Sxiv:Kunst sticky=on layer=below border=off focus=off manage=off #rectangle=250x250+1055+60



